site_name: Samer Lahoud
site_author: Samer Lahoud
site_description: Samer Lahoud personal website.
theme_dir: custom_yeti
copyright: Samer Lahoud - Based on <a href="http://getbootstrap.com/">Bootstrap</a> - 
pages:
- Home: index.md
- Research Activities: research.md
- Publications: publications.md
- Contact: contact.md
extra:
    links:
        - <a href="http://scholar.google.com/citations?user=Fnkc3a4AAAAJ&hl=en/">Google Scholar</a>
        - <a href="http://www-adopnet.irisa.fr">Research Team</a>
        - <a href="http://wiki.lahoud.fr/">Wiki</a>
google_analytics: ['UA-6644003-1', 'samer.lahoud.fr']

    